AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Load Balancer for Open WebUI with HTTPS support'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name prefix for resources
    Default: open-webui
  
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the load balancer
  
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets for the load balancer
  
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the load balancer
  
  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for HTTPS (leave empty to disable HTTPS)
    Default: ''
    AllowedPattern: ^(arn:aws:acm:.*)?$
    ConstraintDescription: Must be a valid ACM certificate ARN or empty
  
  HealthCheckPath:
    Type: String
    Description: Health check path
    Default: /health
  
  HealthCheckIntervalSeconds:
    Type: Number
    Description: Health check interval in seconds
    Default: 30
    MinValue: 5
    MaxValue: 300
  
  HealthCheckTimeoutSeconds:
    Type: Number
    Description: Health check timeout in seconds
    Default: 5
    MinValue: 2
    MaxValue: 120
  
  HealthyThresholdCount:
    Type: Number
    Description: Number of consecutive successful health checks
    Default: 2
    MinValue: 2
    MaxValue: 10
  
  UnhealthyThresholdCount:
    Type: Number
    Description: Number of consecutive failed health checks
    Default: 3
    MinValue: 2
    MaxValue: 10
  
  DeregistrationDelay:
    Type: Number
    Description: Deregistration delay in seconds
    Default: 30
    MinValue: 0
    MaxValue: 3600
  
  EnableAccessLogs:
    Type: String
    Description: Enable ALB access logs to S3
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  
  AccessLogsBucket:
    Type: String
    Description: S3 bucket name for access logs (required if EnableAccessLogs is true)
    Default: ''

Conditions:
  EnableAccessLogging: !Equals [!Ref EnableAccessLogs, 'true']
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  # ============================================================================
  # Application Load Balancer
  # ============================================================================
  
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroup
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: deletion_protection.enabled
          Value: 'false'
        - Key: routing.http2.enabled
          Value: 'true'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: routing.http.desync_mitigation_mode
          Value: defensive
        - Key: routing.http.x_amzn_tls_version_and_cipher_suite.enabled
          Value: 'true'
        - Key: routing.http.xff_client_port.enabled
          Value: 'true'
        - !If
          - EnableAccessLogging
          - Key: access_logs.s3.enabled
            Value: 'true'
          - !Ref AWS::NoValue
        - !If
          - EnableAccessLogging
          - Key: access_logs.s3.bucket
            Value: !Ref AccessLogsBucket
          - !Ref AWS::NoValue
        - !If
          - EnableAccessLogging
          - Key: access_logs.s3.prefix
            Value: !Sub ${EnvironmentName}-alb
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-alb
        - Key: Environment
          Value: !Ref EnvironmentName

  # ============================================================================
  # Target Group
  # ============================================================================
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-tg
      VpcId: !Ref VPC
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutSeconds
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      Matcher:
        HttpCode: '200'
      
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: !Ref DeregistrationDelay
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '86400'
        - Key: load_balancing.algorithm.type
          Value: least_outstanding_requests
      
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-tg
        - Key: Environment
          Value: !Ref EnvironmentName

  # ============================================================================
  # HTTPS Listener (Optional)
  # ============================================================================
  
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # ============================================================================
  # HTTP Listener (Redirect to HTTPS)
  # ============================================================================
  
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions: !If
        - HasCertificate
        - - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: '443'
              StatusCode: HTTP_301
        - - Type: forward
            TargetGroupArn: !Ref TargetGroup

  # ============================================================================
  # CloudWatch Alarms
  # ============================================================================
  
  UnhealthyTargetAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-unhealthy-targets
      AlarmDescription: Alert when target group has unhealthy targets
      MetricName: UnHealthyHostCount
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
        - Name: TargetGroup
          Value: !GetAtt TargetGroup.TargetGroupFullName
      TreatMissingData: notBreaching
  
  TargetResponseTimeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-response-time
      AlarmDescription: Alert when target response time is high
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
        - Name: TargetGroup
          Value: !GetAtt TargetGroup.TargetGroupFullName
      TreatMissingData: notBreaching
  
  HTTPCodeTarget5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-target-5xx-errors
      AlarmDescription: Alert when target returns 5XX errors
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
        - Name: TargetGroup
          Value: !GetAtt TargetGroup.TargetGroupFullName
      TreatMissingData: notBreaching

Outputs:
  LoadBalancerArn:
    Description: ARN of the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
  
  LoadBalancerDNSName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  
  LoadBalancerURL:
    Description: URL of the Application Load Balancer
    Value: !Sub https://${ApplicationLoadBalancer.DNSName}
  
  TargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref TargetGroup
  
  HTTPSListenerArn:
    Condition: HasCertificate
    Description: ARN of the HTTPS Listener
    Value: !Ref HTTPSListener
  
  HTTPListenerArn:
    Description: ARN of the HTTP Listener
    Value: !Ref HTTPListener
