AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch monitoring and logging for Open WebUI deployment'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name prefix for resources
    Default: open-webui
  
  ECSCluster:
    Type: String
    Description: ECS Cluster name
  
  ECSService:
    Type: String
    Description: ECS Service name
  
  LogRetentionDays:
    Type: Number
    Description: Number of days to retain logs
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
  
  AlarmEmail:
    Type: String
    Description: Email address for alarm notifications (optional)
    Default: ''
    AllowedPattern: ^([\w\.\-]+@[\w\.\-]+\.\w+)?$
    ConstraintDescription: Must be a valid email address or empty

Conditions:
  CreateSNSTopic: !Not [!Equals [!Ref AlarmEmail, '']]

Resources:
  # ============================================================================
  # KMS Key for CloudWatch Logs Encryption
  # ============================================================================
  
  LogsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS key for ${EnvironmentName} CloudWatch Logs encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: !Sub logs.${AWS::Region}.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:CreateGrant
              - kms:DescribeKey
            Resource: '*'
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-logs-kms-key
        - Key: Environment
          Value: !Ref EnvironmentName
  
  LogsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${EnvironmentName}-logs
      TargetKeyId: !Ref LogsKMSKey

  # ============================================================================
  # CloudWatch Log Groups
  # ============================================================================
  
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/${EnvironmentName}/application
      RetentionInDays: !Ref LogRetentionDays
      KmsKeyId: !GetAtt LogsKMSKey.Arn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-application-logs
        - Key: Environment
          Value: !Ref EnvironmentName
  
  ErrorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/${EnvironmentName}/errors
      RetentionInDays: !Ref LogRetentionDays
      KmsKeyId: !GetAtt LogsKMSKey.Arn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-error-logs
        - Key: Environment
          Value: !Ref EnvironmentName

  # ============================================================================
  # Metric Filters for Error Detection
  # ============================================================================
  
  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '[time, request_id, event_type = ERROR*, ...]'
      LogGroupName: !Ref ApplicationLogGroup
      MetricTransformations:
        - MetricName: ApplicationErrors
          MetricNamespace: !Sub ${EnvironmentName}/Application
          MetricValue: '1'
          DefaultValue: 0
          Unit: Count
  
  CriticalErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '[time, request_id, event_type = CRITICAL*, ...]'
      LogGroupName: !Ref ApplicationLogGroup
      MetricTransformations:
        - MetricName: CriticalErrors
          MetricNamespace: !Sub ${EnvironmentName}/Application
          MetricValue: '1'
          DefaultValue: 0
          Unit: Count

  # ============================================================================
  # SNS Topic for Alarms (Optional)
  # ============================================================================
  
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSNSTopic
    Properties:
      TopicName: !Sub ${EnvironmentName}-alarms
      DisplayName: !Sub ${EnvironmentName} Alarms
      KmsMasterKeyId: alias/aws/sns
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-alarm-topic
        - Key: Environment
          Value: !Ref EnvironmentName
  
  AlarmTopicSubscription:
    Type: AWS::SNS::Subscription
    Condition: CreateSNSTopic
    Properties:
      Protocol: email
      TopicArn: !Ref AlarmTopic
      Endpoint: !Ref AlarmEmail

  # ============================================================================
  # CloudWatch Alarms - ECS Service
  # ============================================================================
  
  ECSServiceCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ecs-high-cpu
      AlarmDescription: Alert when ECS service CPU utilization is high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSCluster
        - Name: ServiceName
          Value: !Ref ECSService
      AlarmActions: !If
        - CreateSNSTopic
        - [!Ref AlarmTopic]
        - []
      TreatMissingData: notBreaching
  
  ECSServiceMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ecs-high-memory
      AlarmDescription: Alert when ECS service memory utilization is high
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSCluster
        - Name: ServiceName
          Value: !Ref ECSService
      AlarmActions: !If
        - CreateSNSTopic
        - [!Ref AlarmTopic]
        - []
      TreatMissingData: notBreaching
  
  ECSServiceRunningTasksAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-ecs-no-running-tasks
      AlarmDescription: Alert when ECS service has no running tasks
      MetricName: RunningTaskCount
      Namespace: ECS/ContainerInsights
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSCluster
        - Name: ServiceName
          Value: !Ref ECSService
      AlarmActions: !If
        - CreateSNSTopic
        - [!Ref AlarmTopic]
        - []
      TreatMissingData: breaching

  # ============================================================================
  # CloudWatch Alarms - Application Errors
  # ============================================================================
  
  ApplicationErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-application-errors
      AlarmDescription: Alert when application errors are detected
      MetricName: ApplicationErrors
      Namespace: !Sub ${EnvironmentName}/Application
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: !If
        - CreateSNSTopic
        - [!Ref AlarmTopic]
        - []
      TreatMissingData: notBreaching
  
  CriticalErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-critical-errors
      AlarmDescription: Alert when critical errors are detected
      MetricName: CriticalErrors
      Namespace: !Sub ${EnvironmentName}/Application
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: !If
        - CreateSNSTopic
        - [!Ref AlarmTopic]
        - []
      TreatMissingData: notBreaching

  # ============================================================================
  # CloudWatch Dashboard
  # ============================================================================
  
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${EnvironmentName}-dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", {"stat": "Average", "label": "CPU"}],
                  [".", "MemoryUtilization", {"stat": "Average", "label": "Memory"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "ECS Service Utilization",
                "period": 300,
                "yAxis": {
                  "left": {
                    "min": 0,
                    "max": 100
                  }
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["ECS/ContainerInsights", "RunningTaskCount", {"stat": "Average"}],
                  [".", "DesiredTaskCount", {"stat": "Average"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "ECS Task Count",
                "period": 300
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "TargetResponseTime", {"stat": "Average"}],
                  ["...", {"stat": "p99"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "ALB Response Time",
                "period": 300,
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "RequestCount", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_2XX_Count", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_4XX_Count", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_5XX_Count", {"stat": "Sum"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "ALB Request Metrics",
                "period": 300
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "HealthyHostCount", {"stat": "Average"}],
                  [".", "UnHealthyHostCount", {"stat": "Average"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Target Health",
                "period": 60
              }
            },
            {
              "type": "log",
              "properties": {
                "query": "SOURCE '${ApplicationLogGroup}'\n| fields @timestamp, @message\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Application Logs",
                "stacked": false
              }
            }
          ]
        }

Outputs:
  ApplicationLogGroup:
    Description: Application log group name
    Value: !Ref ApplicationLogGroup
  
  ErrorLogGroup:
    Description: Error log group name
    Value: !Ref ErrorLogGroup
  
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MonitoringDashboard}
  
  AlarmTopicArn:
    Description: SNS Topic ARN for alarms
    Value: !If
      - CreateSNSTopic
      - !Ref AlarmTopic
      - 'N/A'
  
  LogsKMSKeyId:
    Description: KMS Key ID for logs encryption
    Value: !Ref LogsKMSKey
